@url = http://localhost:8080

# @name HelloWorld
GET {{url}}/
###

# @name GetLists
GET {{url}}/list
###

# @name CreateList
POST {{url}}/list
Content-Type: application/json

{
  "name": "Turtles",
  "items": [
    {
      "title": "Snapper"
    },
    {
      "title": "Razorback"
    },
    {
      "title": "Box",
      "status": true
    },
    {

    }
  ]
}
###

# @name CreateListWithBadBody
POST {{url}}/list
Content-Type: application/json

{
  "name": "Some list"
}
###

@listId = {{GetLists.response.body.0._id}}
# @name GetListById
GET {{url}}/list/{{listId}}
###

# @name FailToGetListById
GET {{url}}/list/this_id_doesnt_exist
###

# @name DeleteListById
DELETE {{url}}/list/{{listId}}
###

# @name FailToGetListToDelete
DELETE {{url}}/list/this_id_doesnt_exist
###

@animalListId = {{GetLists.response.body.2._id}}

# @name UpdateFirstList
PATCH {{url}}/list/{{animalListId}}
Content-Type: application/json

{
  "name": "Seahorses",
  "items": [
    {
      "title": "Randy"
    },
    { "title": "Flatface" },
    { "title": "Shortface" },
    { "title": "Longface" },
    { "title": "Longface" }
  ]
}
###